/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_derycke_pieter_com_COM */

#ifndef _Included_be_derycke_pieter_com_COM
#define _Included_be_derycke_pieter_com_COM
#ifdef __cplusplus
extern "C" {
#endif
#undef be_derycke_pieter_com_COM_CLSCTX_INPROC_SERVER
#define be_derycke_pieter_com_COM_CLSCTX_INPROC_SERVER 1i64
#undef be_derycke_pieter_com_COM_CLSCTX_INPROC_HANDLER
#define be_derycke_pieter_com_COM_CLSCTX_INPROC_HANDLER 2i64
/*
 * Class:     be_derycke_pieter_com_COM
 * Method:    CoCreateInstance
 * Signature: (Lbe/derycke/pieter/com/CLSID;JJLbe/derycke/pieter/com/IID;)Lbe/derycke/pieter/com/COMReference;
 */
JNIEXPORT jobject JNICALL Java_be_derycke_pieter_com_COM_CoCreateInstance
  (JNIEnv *, jclass, jobject, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
