/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDeviceTransfert */

#ifndef _Included_jmtp_PortableDeviceTransfert
#define _Included_jmtp_PortableDeviceTransfert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDeviceTransfert
 * Method:    transfertToHost
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljmtp/PortableDevice;)Z
 */
JNIEXPORT jboolean JNICALL Java_jmtp_PortableDeviceTransfert_transfertToHost
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     jmtp_PortableDeviceTransfert
 * Method:    transfertFromHost
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjmtp/PortableDevice;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_PortableDeviceTransfert_transfertFromHost
  (JNIEnv *, jclass, jstring, jstring, jstring, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
