/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDeviceProperties */

#ifndef _Included_jmtp_PortableDeviceProperties
#define _Included_jmtp_PortableDeviceProperties
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDeviceProperties
 * Method:    getPropertyAttributes
 * Signature: (Ljava/lang/String;Ljmtp/PropertyKey;)Ljmtp/PortableDeviceValues;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceProperties_getPropertyAttributes
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jmtp_PortableDeviceProperties
 * Method:    getValues
 * Signature: (Ljava/lang/String;Ljmtp/PortableDeviceKeyCollection;)Ljmtp/PortableDeviceValues;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceProperties_getValues
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jmtp_PortableDeviceProperties
 * Method:    setValues
 * Signature: (Ljava/lang/String;Ljmtp/PortableDeviceValues;)Ljmtp/PortableDeviceValues;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceProperties_setValues
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
