/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDevice */

#ifndef _Included_jmtp_PortableDevice
#define _Included_jmtp_PortableDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDevice
 * Method:    getDeviceFriendlyName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_PortableDevice_getDeviceFriendlyName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmtp_PortableDevice
 * Method:    getDeviceManufacturer
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_PortableDevice_getDeviceManufacturer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmtp_PortableDevice
 * Method:    getDeviceDescription
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_PortableDevice_getDeviceDescription
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmtp_PortableDevice
 * Method:    openImpl
 * Signature: (Ljmtp/PortableDeviceValues;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDevice_openImpl
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDevice
 * Method:    closeImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDevice_closeImpl
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDevice
 * Method:    getDeviceContent
 * Signature: ()Ljmtp/PortableDeviceContent;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDevice_getDeviceContent
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDevice
 * Method:    sendCommand
 * Signature: (Ljmtp/PortableDeviceValues;)Ljmtp/PortableDeviceValues;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDevice_sendCommand
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
