/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDeviceContent */

#ifndef _Included_jmtp_PortableDeviceContent
#define _Included_jmtp_PortableDeviceContent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDeviceContent
 * Method:    createObjectWithPropertiesAndData
 * Signature: (Ljmtp/PortableDeviceValues;Ljava/io/File;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_PortableDeviceContent_createObjectWithPropertiesAndData
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceContent
 * Method:    createObjectWithPropertiesOnly
 * Signature: (Ljmtp/PortableDeviceValues;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_PortableDeviceContent_createObjectWithPropertiesOnly
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceContent
 * Method:    delete
 * Signature: (ILjmtp/PortableDevicePropVariantCollection;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceContent_delete
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jmtp_PortableDeviceContent
 * Method:    listChildObjects
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jmtp_PortableDeviceContent_listChildObjects
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmtp_PortableDeviceContent
 * Method:    getProperties
 * Signature: ()Ljmtp/PortableDeviceProperties;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceContent_getProperties
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDeviceContent
 * Method:    getObjectIDsFromPersistentUniqueIDs
 * Signature: (Ljmtp/PortableDevicePropVariantCollection;)Ljmtp/PortableDevicePropVariantCollection;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceContent_getObjectIDsFromPersistentUniqueIDs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceContent
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceContent_cancel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
