/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDeviceManager */

#ifndef _Included_jmtp_PortableDeviceManager
#define _Included_jmtp_PortableDeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDeviceManager
 * Method:    refreshDeviceList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceManager_refreshDeviceList
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDeviceManager
 * Method:    getDevicesImpl
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jmtp_PortableDeviceManager_getDevicesImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
