/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDeviceValues */

#ifndef _Included_jmtp_PortableDeviceValues
#define _Included_jmtp_PortableDeviceValues
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_clear
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jmtp_PortableDeviceValues_count
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    setStringValue
 * Signature: (Ljmtp/PropertyKey;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_setStringValue
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    getStringValue
 * Signature: (Ljmtp/PropertyKey;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_PortableDeviceValues_getStringValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    setGuidValue
 * Signature: (Ljmtp/PropertyKey;Lbe/derycke/pieter/com/Guid;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_setGuidValue
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    getGuidValue
 * Signature: (Ljmtp/PropertyKey;)Lbe/derycke/pieter/com/Guid;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceValues_getGuidValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    setUnsignedIntegerValue
 * Signature: (Ljmtp/PropertyKey;J)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_setUnsignedIntegerValue
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    getUnsignedIntegerValue
 * Signature: (Ljmtp/PropertyKey;)J
 */
JNIEXPORT jlong JNICALL Java_jmtp_PortableDeviceValues_getUnsignedIntegerValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    setPortableDeviceValuesCollectionValue
 * Signature: (Ljmtp/PropertyKey;Ljmtp/PortableDevicePropVariantCollection;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_setPortableDeviceValuesCollectionValue
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    getPortableDeviceValuesCollectionValue
 * Signature: (Ljmtp/PropertyKey;)Ljmtp/PortableDevicePropVariantCollection;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceValues_getPortableDeviceValuesCollectionValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    setBoolValue
 * Signature: (Ljmtp/PropertyKey;Z)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_setBoolValue
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    getBoolValue
 * Signature: (Ljmtp/PropertyKey;)Z
 */
JNIEXPORT jboolean JNICALL Java_jmtp_PortableDeviceValues_getBoolValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    setFloateValue
 * Signature: (Ljmtp/PropertyKey;F)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_setFloateValue
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    getFloatValue
 * Signature: (Ljmtp/PropertyKey;)F
 */
JNIEXPORT jfloat JNICALL Java_jmtp_PortableDeviceValues_getFloatValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    setErrorValue
 * Signature: (Ljmtp/PropertyKey;Lbe/derycke/pieter/com/COMException;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_setErrorValue
  (JNIEnv *, jobject, jobject, jthrowable);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    getErrorValue
 * Signature: (Ljmtp/PropertyKey;)Lbe/derycke/pieter/com/COMException;
 */
JNIEXPORT jthrowable JNICALL Java_jmtp_PortableDeviceValues_getErrorValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    setUnsignedLargeIntegerValue
 * Signature: (Ljmtp/PropertyKey;Ljava/math/BigInteger;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_setUnsignedLargeIntegerValue
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    getUnsignedLargeIntegerValue
 * Signature: (Ljmtp/PropertyKey;)Ljava/math/BigInteger;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceValues_getUnsignedLargeIntegerValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    setBufferValue
 * Signature: (Ljmtp/PropertyKey;[B)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceValues_setBufferValue
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     jmtp_PortableDeviceValues
 * Method:    getBufferValue
 * Signature: (Ljmtp/PropertyKey;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jmtp_PortableDeviceValues_getBufferValue
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
