/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDeviceKeyCollection */

#ifndef _Included_jmtp_PortableDeviceKeyCollection
#define _Included_jmtp_PortableDeviceKeyCollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDeviceKeyCollection
 * Method:    add
 * Signature: (Ljmtp/PropertyKey;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceKeyCollection_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceKeyCollection
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceKeyCollection_clear
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDeviceKeyCollection
 * Method:    count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jmtp_PortableDeviceKeyCollection_count
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDeviceKeyCollection
 * Method:    getAt
 * Signature: (J)Ljmtp/PropertyKey;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceKeyCollection_getAt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jmtp_PortableDeviceKeyCollection
 * Method:    removeAt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceKeyCollection_removeAt
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
