/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDevicePropVariantCollection */

#ifndef _Included_jmtp_PortableDevicePropVariantCollection
#define _Included_jmtp_PortableDevicePropVariantCollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDevicePropVariantCollection
 * Method:    add
 * Signature: (Ljmtp/PropVariant;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDevicePropVariantCollection_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDevicePropVariantCollection
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDevicePropVariantCollection_clear
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDevicePropVariantCollection
 * Method:    count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jmtp_PortableDevicePropVariantCollection_count
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDevicePropVariantCollection
 * Method:    getAt
 * Signature: (J)Ljmtp/PropVariant;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDevicePropVariantCollection_getAt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jmtp_PortableDevicePropVariantCollection
 * Method:    removeAt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDevicePropVariantCollection_removeAt
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
